const cards = [
	{
		key: 'proc_mgmt',
		label: 'Управление процессами',
		icon: 'mdi-folder-outline',
		children: [
			{
				key: 'biz_proc',
				label: 'Бизнес-процесс',
				icon: '',
				children: [
					{ key: 'bp_desc', label: 'Общее описание', icon: '', children: [] },
					{ key: 'bp_gateways', label: 'Шлюзы', icon: '', children: [] },
					{ key: 'bp_vars', label: 'Переменные', icon: '', children: [] },
					{ key: 'bp_functions', label: 'Функции', icon: '', children: [] },
					{
						key: 'bp_links',
						label: 'Связи',
						icon: '',
						children: [
							{ key: 'link_id', label: 'Идентификатор', icon: '' },
							{ key: 'link_name', label: 'Название', icon: '' },
							{ key: 'link_source', label: 'Источник', icon: '' },
							{ key: 'link_target', label: 'Приемник', icon: '' },
							{ key: 'link_type', label: 'Тип связи', icon: '' },
							{ key: 'link_style', label: 'Стиль', icon: '' },
							{ key: 'link_status', label: 'Статус связи', icon: '' },
							{ key: 'link_desc', label: 'Описание связи', icon: '' },
							{ key: 'link_points', label: 'Точки', icon: '' },
							{
								key: 'link_func_id',
								label: 'Идентификатор связанной функции',
								icon: '',
							},
						],
					},
					{ key: 'bp_journal', label: 'Журнал', icon: '', children: [] },
					{
						key: 'bp_queue',
						label: 'Очередь сообщений процесса',
						icon: '',
						children: [],
					},
				],
			},
		],
	},
	{
		key: 'sys_cards',
		label: 'Системные карточки',
		icon: 'mdi-folder-outline',
		children: [
			{
				key: 'file_card_ver',
				label: 'Карточка файла с версиями',
				icon: '',
				children: [
					{
						key: 'file_info',
						label: 'Общая информация',
						icon: '',
						children: [
							{ key: 'f_name', label: 'Название файла', icon: '' },
							{
								key: 'f_parent_id',
								label: 'Идентификатор родительской карточки',
								icon: '',
							},
							{
								key: 'f_curr_ver_id',
								label: 'Идентификатор текущей версии',
								icon: '',
							},
							{
								key: 'f_next_ver_num',
								label: 'Номер следующей версии',
								icon: '',
							},
							{ key: 'f_path', label: 'Путь к файлу', icon: '' },
							{
								key: 'f_curr_ver_num',
								label: 'Номер текущей версии',
								icon: '',
							},
							{
								key: 'f_user_id',
								label: 'Идентификатор пользователя',
								icon: '',
							},
							{ key: 'f_ext_card', label: 'Карточка расширения', icon: '' },
							{ key: 'f_barcode', label: 'Штрих-код', icon: '' },
							{ key: 'f_lock_date', label: 'Дата блокировки', icon: '' },
							{
								key: 'f_change_date',
								label: 'Дата изменения файла текущей версии',
								icon: '',
							},
						],
					},
					{
						key: 'file_comments',
						label: 'Комментарии файла',
						icon: '',
						children: [
							{ key: 'fc_text', label: 'Комментарий', icon: '' },
							{ key: 'fc_author', label: 'Автор комментария', icon: '' },
							{ key: 'fc_date', label: 'Дата создания', icon: '' },
						],
					},
					{
						key: 'file_versions',
						label: 'Версии',
						icon: '',
						children: [
							{ key: 'fv_uid', label: 'Уникальный номер версии', icon: '' },
							{ key: 'fv_author', label: 'Автор версии', icon: '' },
							{ key: 'fv_file_id', label: 'Идентификатор файла', icon: '' },
							{ key: 'fv_num', label: 'Номер версии', icon: '' },
							{ key: 'fv_ext_card', label: 'Карточка расширения', icon: '' },
						],
					},
					{
						key: 'file_assoc',
						label: 'Ассоциированные файлы',
						icon: '',
						children: [],
					},
					{
						key: 'file_ver_comm',
						label: 'Комментарии версии',
						icon: '',
						children: [],
					},
				],
			},
		],
	},
	{
		key: 'base_objects',
		label: 'Базовые объекты',
		icon: 'mdi-folder-outline',
		children: [
			{
				key: 'list_task_links',
				label: 'Список ссылок на карточки заданий',
				icon: '',
				children: [],
			},
			{
				key: 'dep_card',
				label: 'Карточка подразделения',
				icon: '',
				children: [],
			},
			{
				key: 'ref_row_card',
				label: 'Карточка строки справочника',
				icon: '',
				children: [
					{
						key: 'ref_main_info',
						label: 'Основная информация',
						icon: '',
						children: [
							{ key: 'ref_link', label: 'Ссылка', icon: '' },
							{ key: 'ref_state', label: 'State', icon: '' },
							{ key: 'ref_view', label: 'Вид', icon: '' },
							{ key: 'ref_trigger', label: 'Создано триггером', icon: '' },
							{
								key: 'ref_access_group',
								label: 'Группа ознакомления',
								icon: '',
							},
						],
					},
					{
						key: 'ref_sys_props',
						label: 'Системные свойства',
						icon: '',
						children: [],
					},
				],
			},
			{ key: 'task_obj', label: 'Задание', icon: '', children: [] },
			{ key: 'server_card', label: 'Карточка сервера', icon: '', children: [] },
			{ key: 'sign_list', label: 'Список подписей', icon: '', children: [] },
			{
				key: 'card_links_list',
				label: 'Список ссылок на карточки',
				icon: '',
				children: [],
			},
			{ key: 'doc_obj', label: 'Документ', icon: '', children: [] },
			{ key: 'poll_list', label: 'Список опросов', icon: '', children: [] },
			{
				key: 'counterparty_dep',
				label: 'Карточка подразделения контрагента',
				icon: '',
				children: [],
			},
			{ key: 'task_group', label: 'Группа заданий', icon: '', children: [] },
			{
				key: 'trust_sys_card',
				label: 'Системная карточка доверенности',
				icon: '',
				children: [],
			},
			{
				key: 'employee_card',
				label: 'Карточка сотрудника',
				icon: '',
				children: [],
			},
			{ key: 'cat_list', label: 'Список категорий', icon: '', children: [] },
			{ key: 'approval_obj', label: 'Согласование', icon: '', children: [] },
			{
				key: 'biz_calendar',
				label: 'Бизнес-календарь',
				icon: '',
				children: [],
			},
			{
				key: 'counterparty_emp',
				label: 'Карточка сотрудника контрагента',
				icon: '',
				children: [],
			},
		],
	},
	{
		key: 'approval_const',
		label: 'Конструктор согласований',
		icon: 'mdi-folder-outline',
		children: [
			{
				key: 'appr_route',
				label: 'Маршрут согласования',
				icon: '',
				children: [
					{ key: 'ar_sys_props', label: 'Системные свойства', icon: '' },
					{ key: 'ar_numbers', label: 'Номера', icon: '' },
					{ key: 'ar_biz_proc', label: 'Бизнес-процессы', icon: '' },
					{ key: 'ar_main_info', label: 'Основная информация', icon: '' },
					{ key: 'ar_map_steps', label: 'Карта этапов', icon: '' },
					{ key: 'ar_states', label: 'Состояния', icon: '' },
					{ key: 'ar_cycle_steps', label: 'Этапы цикла', icon: '' },
				],
			},
			{
				key: 'appr_step',
				label: 'Этап согласования',
				icon: '',
				children: [
					{ key: 'as_sys_props', label: 'Системные свойства', icon: '' },
					{ key: 'as_numbers', label: 'Номера', icon: '' },
					{ key: 'as_biz_proc', label: 'Бизнес-процессы', icon: '' },
					{ key: 'as_main_info', label: 'Основная информация', icon: '' },
					{ key: 'as_approvers', label: 'Согласующие', icon: '' },
					{ key: 'as_decisions', label: 'Решения', icon: '' },
					{ key: 'as_task_settings', label: 'Настройки задания', icon: '' },
					{ key: 'as_states', label: 'Состояния', icon: '' },
					{
						key: 'as_extra_settings',
						label: 'Дополнительные настройки',
						icon: '',
					},
					{ key: 'as_curr_appr', label: 'Текущие согласующие', icon: '' },
					{
						key: 'as_extra_appr',
						label: 'Дополнительные согласующие',
						icon: '',
					},
				],
			},
			{
				key: 'appr_result',
				label: 'Результат согласования',
				icon: '',
				children: [
					{ key: 'ares_main_info', label: 'Основная информация', icon: '' },
				],
			},
		],
	},
]
export { cards }
