import { uid } from 'quasar'

const configs = [
	{
		id: 'root',
		text: 'Конфигурации',
		drag: false,
		drop: true,
		children: [
			{
				id: 'one',
				text: 'Config 1',
				drag: true,
				drop: false,
				icon: 'mdi-code-braces',
				env: 'dev',
			},
			{
				id: 'two',
				text: 'Config 2',
				drag: true,
				drop: false,
				icon: 'mdi-code-braces',
				env: 'prod',
			},
			{
				id: 'three',
				text: 'Config 3',
				drag: true,
				drop: false,
				icon: 'mdi-code-braces',
				env: 'test',
			},
		],
	},
]

const servers = [
	{
		id: 'root',
		text: 'Серверы',
		drag: false,
		drop: true,
		children: [
			{
				id: uid(),
				text: 'DVM',
				icon: 'mdi-penguin',
				env: 'dev',
				drag: true,
				drop: false,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: '103pc0103',
				icon: 'mdi-penguin',
				env: 'test',
				drag: true,
				drop: false,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: '102pc0102',
				icon: 'mdi-microsoft-windows-classic',
				env: 'test',
				drag: true,
				drop: false,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: '104pc0104',
				icon: 'mdi-penguin',
				env: 'prod',
				drag: true,
				drop: false,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-penguin',
				env: 'dev',
				drag: true,
				drop: false,
				text: '106pc0106',
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-microsoft-windows-classic',
				env: 'test',
				drag: true,
				drop: false,
				text: 'DV-test',
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-penguin',
				env: 'test',
				drag: true,
				drop: false,
				text: 'DVM-new',
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-penguin',
				env: 'dev',
				drag: true,
				drop: false,
				text: 'DV-main',
				selected: false,
				children: [],
			},
		],
	},
]
export { configs, servers }
