import { uid } from 'quasar'

const tree = [
	{
		id: 'servers',
		text: 'Серверы',
		drag: false,
		drop: true,
		type: 0,
		children: [
			{
				id: uid(),
				text: 'DVM',
				psevdo: 'DVM-text',
				system: 'Arch Linux',
				type: 3,
				icon: 'mdi-arch',
				env: 'dev',
				drag: true,
				drop: false,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: '103pc0103',
				psevdo: 'test server',
				system: 'Debian',
				type: 3,
				icon: 'mdi-debian',
				env: 'test',
				drag: true,
				drop: false,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: 'Кластер 1',
				psevdo: 'My cluster',
				system: '--',
				type: 4,
				icon: 'mdi-folder-outline',
				drag: true,
				drop: true,
				selected: false,
				children: [
					{
						id: uid(),
						text: '102pc0102',
						psevdo: 'second test',
						system: 'Microsoft Windows',
						type: 3,
						icon: 'mdi-microsoft-windows',
						env: 'test',
						drag: true,
						drop: false,
						selected: false,
						children: [],
					},
					{
						id: uid(),
						text: '104pc0104',
						psevdo: 'Prod server',
						system: 'Centos',
						type: 3,
						icon: 'mdi-centos',
						env: 'prod',
						drag: true,
						drop: false,
						selected: false,
						children: [],
					},
				],
			},
			{
				id: uid(),
				icon: 'mdi-penguin',
				env: 'dev',
				drag: true,
				drop: false,
				text: '106pc0106',
				psevdo: 'devoloper',
				system: 'Linux',
				type: 3,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-microsoft-windows',
				env: 'test',
				drag: true,
				drop: false,
				text: 'DV-test',
				psevdo: 'DV-test',
				system: 'Microsoft Windows',
				type: 3,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-penguin',
				env: 'test',
				drag: true,
				text: 'DVM-new',
				psevdo: 'DVM-new',
				system: 'Linux',
				drop: false,
				type: 3,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				icon: 'mdi-penguin',
				env: 'dev',
				drag: true,
				drop: false,
				text: 'DV-main',
				psevdo: 'Main',
				system: 'Linux',
				type: 3,
				selected: false,
				children: [],
			},
		],
	},
]

export { tree }
